name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: Dyalog 
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to Fun APL Programs! What is your issue?"
        pr-message: "Thank you to your contribution to Fun APL Programs!"
